import openpyxl
import pytest
from PIL import Image
from hap_converter.engine import change_request, pipeline
from hap_converter.engine.xlsx_exporter import write_fcu_xlsx

DETAILS = {
    "project": "Avarra by Palace",
    "project_no": "MLD",
    "stage": "100 % DD",
    "discipline": "MEP",
    "author": "SA",
    "checked": "FA",
    "revision": "2",
    "date": "20.04.2026",
}


def unit_row(name, coil="9.2"):
    row = [""] * 14
    row[0], row[1], row[2], row[3] = name, "178.2", coil, "8.6"
    row[5], row[6], row[7] = "23.5 / 16.7", "13.2 / 12.5", "0.24"
    row[8], row[10] = "51.63", coil
    return row


def space_row(name, flow="689"):
    row = [""] * 14
    row[0], row[1], row[4] = name, "178.2", flow
    return row


@pytest.fixture
def existing_xlsx(tmp_path, config):
    """A schedule this app produced: 2 units (4 rows) + embedded logo."""
    logo = tmp_path / "logo.png"
    Image.new("RGB", (300, 100), (10, 40, 80)).save(logo)
    rows = [
        unit_row("#01-Corridor"), space_row("#01-Corridor"),
        unit_row("#02-Lobby"), space_row("#02-Lobby"),
    ]
    path = tmp_path / "HAP Zone Sizing Summary.xlsx"
    write_fcu_xlsx(dict(DETAILS, logo_path=str(logo)), config.csv_columns, rows, path)
    return path


def test_load_schedule_reads_rows_and_units(existing_xlsx, config):
    schedule = change_request.load_schedule(existing_xlsx, config)
    assert schedule.row_count == 4
    assert schedule.unit_names == {"#01-Corridor", "#02-Lobby"}
    assert schedule.column_header == config.csv_columns


def test_rejects_workbook_from_another_tool(tmp_path, config):
    wb = openpyxl.Workbook()
    wb.active["A1"] = "Some other report"
    other = tmp_path /"not_ours.xlsx"
    wb.save(other)
    with pytest.raises(change_request.ScheduleFormatError, match="not generated by HAPExt"):
        change_request.load_schedule(other, config)


def test_rejects_mismatched_columns(existing_xlsx, config):
    wb = openpyxl.load_workbook(existing_xlsx)
    wb.active.cell(row=6, column=3, value="Something Else")
    wb.save(existing_xlsx)
    with pytest.raises(change_request.ScheduleFormatError, match="column 3"):
        change_request.load_schedule(existing_xlsx, config)


def test_unit_blocks_group_spaces_with_their_unit():
    rows = [unit_row("A"), space_row("A1"), space_row("A2"), unit_row("B"), space_row("B1")]
    blocks = change_request.unit_blocks(rows)
    assert [len(b) for b in blocks] == [3, 2]


def test_select_new_blocks_skips_units_already_present(existing_xlsx, config):
    schedule = change_request.load_schedule(existing_xlsx, config)
    new_rows = [
        unit_row("#01-Corridor"), space_row("#01-Corridor"),   # already there
        unit_row("#03-Store"), space_row("#03-Store"),         # new
    ]
    blocks, skipped = change_request.select_new_blocks(schedule, new_rows)
    assert len(blocks) == 1
    assert blocks[0][0][0] == "#03-Store"
    assert skipped == ["#01-Corridor"]


def test_append_preserves_header_logo_and_existing_rows(existing_xlsx, tmp_path, config):
    schedule = change_request.load_schedule(existing_xlsx, config)
    blocks = [[unit_row("#03-Store", coil="4.4"), space_row("#03-Store", "120")]]
    out = change_request.append_blocks(schedule, blocks, tmp_path / "updated.xlsx")

    ws = openpyxl.load_workbook(out).active
    # header block untouched
    assert ws["A1"].value == "FCU SCHEDULE"
    assert ws["B2"].value == "Avarra by Palace"
    assert ws["H5"].value == "20.04.2026"
    assert len(ws._images) == 1                      # company logo preserved
    merged = {str(r) for r in ws.merged_cells.ranges}
    assert "A1:F1" in merged and "G1:N1" in merged

    # existing rows unchanged, new rows appended after them
    assert ws.cell(row=7, column=1).value == "#01-Corridor"
    assert ws.cell(row=10, column=1).value == "#02-Lobby"
    assert ws.cell(row=11, column=1).value == "#03-Store"
    assert ws.cell(row=11, column=3).value == "4.4"
    assert ws.cell(row=12, column=5).value == "120"

    # new unit row highlighted + marked, existing row not
    assert ws.cell(row=11, column=1).fill.fgColor.rgb.endswith(change_request.NEW_ROW_FILL)
    assert ws.cell(row=11, column=14).value == change_request.NEW_ROW_NOTE
    assert ws.cell(row=7, column=14).value in (None, "")


def test_pipeline_appends_revised_pdf(existing_xlsx, sample_pdf, tmp_path, config):
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    result = pipeline.convert_change_request(
        str(existing_xlsx), str(sample_pdf), str(out_dir), config
    )
    assert result.ok, result.issues
    assert result.stats["existing_rows"] == 4
    assert result.stats["new_units"] == 3       # sample_pdf has 3 units
    assert result.stats["new_rows"] == 7        # 3 unit rows + 4 space rows
    assert result.stats["total_rows"] == 11
    ws = openpyxl.load_workbook(result.output_path).active
    assert ws.cell(row=11, column=1).value == "#01-9FCorridor1(LIFT)"


def test_pipeline_rejects_when_nothing_new(existing_xlsx, sample_pdf, tmp_path, config):
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    first = pipeline.convert_change_request(
        str(existing_xlsx), str(sample_pdf), str(out_dir), config
    )
    assert first.ok
    # feeding the updated workbook the same PDF again must append nothing
    second = pipeline.convert_change_request(
        str(first.output_path), str(sample_pdf), str(out_dir), config
    )
    assert not second.ok
    assert second.issues[0].field == "no_changes"


def test_pipeline_rejects_bad_pdf_without_touching_excel(existing_xlsx, bad_pdf, tmp_path, config):
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    result = pipeline.convert_change_request(
        str(existing_xlsx), str(bad_pdf), str(out_dir), config
    )
    assert not result.ok
    assert list(out_dir.iterdir()) == []          # nothing written
    assert any("Missing value" in i.description for i in result.issues)


def test_appended_rows_follow_indent_convention(existing_xlsx, tmp_path, config):
    schedule = change_request.load_schedule(existing_xlsx, config)
    blocks = [[unit_row("#04-New"), space_row("#04-New-sub")]]
    out = change_request.append_blocks(schedule, blocks, tmp_path / "indent.xlsx")
    ws = openpyxl.load_workbook(out).active
    assert (ws.cell(row=11, column=1).alignment.indent or 0) == 0  # appended unit row
    assert ws.cell(row=12, column=1).alignment.indent == 3         # appended space row
    assert ws.cell(row=12, column=1).value == "#04-New-sub"        # value untouched
