"""Change Request: append a revised PDF's new line items to an existing
schedule workbook.

Rules (deliberately narrow — this is not an editor):

- The user supplies only two things: the previously generated .xlsx and a
  revised PDF. No project details are collected; the existing header block
  (project, author, revision, date and the embedded company logo) is
  carried over untouched.
- Existing data rows are never modified, reordered or removed. New unit
  blocks are appended after the last row and highlighted.
- A "line item" is one unit block: the unit header row plus its space
  rows. A unit already present in the workbook (matched by name) is
  skipped, so re-running with the same PDF appends nothing.
- The uploaded workbook must be one this app produced; anything else is
  rejected with a clear reason rather than half-appended.
"""

from __future__ import annotations

import shutil
from copy import copy
from dataclasses import dataclass, field
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill

from .config import Config
from .xlsx_exporter import SPACE_NAME_INDENT

TITLE_CELL = "A1"
TITLE_TEXT = "FCU SCHEDULE"
HEADER_ROW = 6          # column titles live here in files we generate
FIRST_DATA_ROW = 7
NEW_ROW_FILL = "E2EFDA"  # soft green highlight for appended rows
NEW_ROW_NOTE = "NEW – Added"

_UNIT_COL = 2   # Total Coil Load: filled on unit rows, blank on space rows
_NAME_COL = 0
_REMARKS_COL = 13


class ScheduleFormatError(Exception):
    """The uploaded workbook is not a schedule this app produced."""


@dataclass
class ScheduleInfo:
    path: Path
    column_header: list[str]
    data_rows: list[list[str]]
    unit_names: set[str] = field(default_factory=set)

    @property
    def row_count(self) -> int:
        return len(self.data_rows)


def _cell_text(value) -> str:
    return "" if value is None else str(value)


def load_schedule(xlsx_path: str | Path, config: Config) -> ScheduleInfo:
    """Read + validate a previously generated schedule workbook."""
    path = Path(xlsx_path)
    try:
        workbook = openpyxl.load_workbook(path, data_only=True)
    except Exception as exc:
        raise ScheduleFormatError(
            f"The file could not be opened as an Excel workbook ({exc})."
        ) from exc

    sheet = workbook.active
    if _cell_text(sheet[TITLE_CELL].value).strip().upper() != TITLE_TEXT:
        raise ScheduleFormatError(
            "This workbook was not generated by HAPExt — cell A1 should read "
            f"'{TITLE_TEXT}'."
        )

    header = [
        _cell_text(sheet.cell(row=HEADER_ROW, column=c).value).strip()
        for c in range(1, len(config.csv_columns) + 1)
    ]
    expected = [c.strip() for c in config.csv_columns]
    if header != expected:
        mismatch = next(
            (
                f"column {i + 1} is {got!r}, expected {want!r}"
                for i, (got, want) in enumerate(zip(header, expected))
                if got != want
            ),
            "the column count differs",
        )
        raise ScheduleFormatError(
            f"The column headings do not match the HAPExt schedule format: {mismatch}."
        )

    data_rows: list[list[str]] = []
    for row in sheet.iter_rows(min_row=FIRST_DATA_ROW, max_col=len(expected)):
        values = [_cell_text(cell.value) for cell in row]
        if any(v.strip() for v in values):
            data_rows.append(values)

    if not data_rows:
        raise ScheduleFormatError("The workbook contains no schedule rows to add to.")

    return ScheduleInfo(
        path=path,
        column_header=header,
        data_rows=data_rows,
        unit_names={
            r[_NAME_COL].strip() for r in data_rows if r[_UNIT_COL].strip()
        },
    )


def unit_blocks(rows: list[list[str]]) -> list[list[list[str]]]:
    """Group flat rows into unit blocks (unit header row + its space rows)."""
    blocks: list[list[list[str]]] = []
    for row in rows:
        is_unit_row = bool(row[_UNIT_COL].strip())
        if is_unit_row or not blocks:
            blocks.append([row])
        else:
            blocks[-1].append(row)
    return blocks


def select_new_blocks(
    schedule: ScheduleInfo, new_rows: list[list[str]]
) -> tuple[list[list[list[str]]], list[str]]:
    """Split the revised PDF's blocks into (to append, skipped unit names)."""
    to_append: list[list[list[str]]] = []
    skipped: list[str] = []
    seen = set(schedule.unit_names)
    for block in unit_blocks(new_rows):
        name = block[0][_NAME_COL].strip()
        if name in seen:
            skipped.append(name)
        else:
            to_append.append(block)
            seen.add(name)
    return to_append, skipped


def append_blocks(
    schedule: ScheduleInfo,
    blocks: list[list[list[str]]],
    output_path: str | Path,
    mark_new: bool = True,
) -> Path:
    """Copy the workbook and append the new blocks, highlighted.

    The copy keeps the original header block, the embedded logo, merged
    cells and every existing row byte-for-byte; only rows after the last
    used row are added.
    """
    output_path = Path(output_path)
    shutil.copyfile(schedule.path, output_path)

    workbook = openpyxl.load_workbook(output_path)
    sheet = workbook.active
    row_index = FIRST_DATA_ROW + schedule.row_count

    template_row = FIRST_DATA_ROW + schedule.row_count - 1  # last existing row
    fill = PatternFill("solid", fgColor=NEW_ROW_FILL)

    for block in blocks:
        for values in block:
            is_unit_row = bool(values[_UNIT_COL].strip())
            for col, value in enumerate(values, start=1):
                cell = sheet.cell(row=row_index, column=col, value=value)
                source = sheet.cell(row=template_row, column=col)
                cell.border = copy(source.border)
                if col == 1:
                    # don't copy the template's indent: set it by row type,
                    # matching the writer (units flush left, spaces stepped in)
                    cell.alignment = Alignment(
                        horizontal="left",
                        vertical="center",
                        indent=0 if is_unit_row else SPACE_NAME_INDENT,
                    )
                else:
                    cell.alignment = copy(source.alignment)
                if mark_new:
                    cell.fill = fill
            if mark_new and values is block[0]:
                note = sheet.cell(row=row_index, column=_REMARKS_COL + 1)
                if not _cell_text(note.value).strip():
                    note.value = NEW_ROW_NOTE
                    note.font = Font(bold=True, size=9, color="4F6B1B")
            row_index += 1

    workbook.save(output_path)
    return output_path
